/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\frontends\astryx\theme\gptload.theme.ts
 * Command: astryx theme build src\frontends\astryx\theme\gptload.theme.ts --out src\frontends\astryx\theme\gptload.theme.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
