import eslintConfigPrettier from 'eslint-config-prettier'
import { defineConfig, globalIgnores } from 'eslint/config'
import reactHooks from 'eslint-plugin-react-hooks'
import stylex from '@stylexjs/eslint-plugin'
import tseslint from 'typescript-eslint'

export default defineConfig(
  globalIgnores([
    'node_modules/**',
    // Generated by `astryx theme build`; freshness is enforced by theme:check.
    'src/frontends/astryx/theme/gptload.{js,d.ts,css}',
    'src/frontends/astryx/theme/gptload.variants.d.ts',
  ]),
  tseslint.configs.recommended,
  // The shared layer stays framework-free; the app is the only consumer.
  {
    files: ['src/shared/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [{ regex: '(^|/)frontends/' }],
        },
      ],
    },
  },
  // React 19 frontend: hooks + compiler diagnostics are errors, StyleX validity
  // is enforced by the design system's own plugin.
  {
    files: ['src/frontends/astryx/**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': reactHooks,
      '@stylexjs': stylex,
    },
    rules: {
      ...reactHooks.configs['recommended-latest'].rules,
      '@stylexjs/valid-styles': 'error',
    },
  },
  eslintConfigPrettier,
)
